### ISSUE TITLE
Remove random_cheer() from the footer of embd.py

### ISSUE THREAD

**Issue by raavann** [raavann/senpai-discord-bot#14]
Remove the random_cheer() from the embd.py in the da1_rem() function.
Also remove avtr parameter from embd.py and getupdates.py inside contests directory as it won't be used after removing footer of the embed.

**Comment by earthprelude** [comment]
I do not see a da1_rem() function in embd.py, is this comment referring to the **embed_1drem()** function?

**Comment by earthprelude** [comment]
To clarify, would you like to remove the set_footer() method of embd in the embed_1drem() and embed_1hrem() functions? (I did not see a da1_rem() function in embds.py.)

**Comment by raavann** [comment]
Yes, apologies to be so vague
but wait, remove set_footer() only in embed_1drem() from ./dscrd/embds.py and not embed_1hrem(),
similarly only remove avatar_url argument only from the block which call embed_1drem()

i.e : 
if( (dtime.time_ -timedelta(hours=28)) < datetime.now() < (dtime.time_ - timedelta(hours=22)) and dtime.day1_rem == False):
                    contest_data.update_rd1((dtime.id_))
                    dtime.day1_rem = True
                    em = embds.embed_1drem(contest_data.get_cont_by_id((dtime.id_)),client.user.avatar_url)
                    print('1d rem sending..',dtime)
                    await send_updates(em,client)

ping me once you're done, i'll merge the changes 💯 

i.e: remove footer from daily update and not from hourly update

**Comment by earthprelude** [comment]
Oh ok thanks for the clarification! I updated the file to only change the embed_1drem() function (daily update)
